#!/bin/bash

#############################################
# EXITS 0 IF THE ITEM NEEDS INSTALLED
# EXITS 1 IF THE ITEM DOES NOT NEED INSTALLED
#############################################

# type: uninstall | install
type=${1}
# location: model | node | py
location=${2}
# name of the package
pkg=${3}
# command: variable
cmd=${4}
# name of the file
name=undefined
# model sub folder
model_location=undefined
# download url
url=undefined
# the path of the active file
path=undefined

# INIT
if [[ $location == model ]]; then
    # Convert commands to array
    cmd_array=($cmd)
    # Set name
    name=${cmd_array[0]}
    # Set model location
    model_location=${cmd_array[1]}
    # Set url
    url=${cmd_array[2]}
    # Set path
    path=$PODDY/active/$location/$model_location/$name
elif [[ $location == node ]]; then
    name=$(basename $cmd)
    url=$cmd
    path=$PODDY/active/$location/$name
elif [[ $location == py ]]; then
    name=$cmd
    path=$PODDY/active/$location/$name
else
    echo "ERROR: Invalid command, only install and uninstall are supported"
    exit 1
fi
# INSTALL
if [[ $type == install]]; then
    # Check if already installed
    if [[ -f $path ]]; then
        echo "STATUS: $pkg already installed, registering to install list"
        # Check if package already exists
        exists="false"
        index=0
        # Sets exists to an index if the line was found
        while IFS=$' \t' read -r line || [ -n "$line" ] do
            if [[ $line == $pkg ]]; then
                exists=$index
            fi
            ((index++))
        done < $path
        if [[ $exist == "false" ]]; then
        # Program not found, adding to list
            command='$a\'${pkg}
            sed -i $command $path
        else
        # Program already installed
            echo "ERROR: $pkg is already in install list" 
            exit 1
        fi
        exit 0
    # File doesn't exist, make it and add package to install list and install package
    else
        if [[ $location == apt ]]; then
        # Install apt
            apt-get -y -qq install $cmd
        elif [[ $location == py ]]; then
        # Install py
            pip install $cmd --quiet
        elif [[ $location == node ]]; then
        # Install node
            if [ ! -d $COMFY/custom_nodes/$name ]; then
                echo "STATUS: Fetching ${name}"
                git clone $url $COMFY/custom_nodes/$name
            fi
        elif [[ $location == model ]]; then
        # Install model
            directory=$COMFY/models/$model_location
            file=$directory/$name
            mkdir -p $directory
            if [[ -f $file ]]; then
            # Bail if already exists
                echo  "WARNING: $name already exists, no need to double flush."
                exit 0
            fi
            # Extract domain name
            domain=$(echo "$full_url" | sed -E 's|(https://)?([^/]+).*|\2|')
            full_url=$url
            domain=$(basename -s ".com" $domain)
            domain=$(basename -s ".co" $domain)
            # Download
            if [[ $domain == "civitai" ]]; then
                token=${CIVITAI:-"none"}
                # CIVITAI
                if [[ $token == "none" ]]; then
                    echo "ERROR: NO FLUSHIN' CIVITAI API FOUND!!! $name requires the CIVITAI environmental variable set"
                    exit 1
                else
                    civitai_url="$url&token=$CIVITAI"
                    echo "downloading $url to $file"
                    wget -O $file $civitai_url
                fi
            else
                # HUGGINGFACE
                echo "downloading $url to $file"
                wget -O $file $url
            fi
        fi
        # Add pkg to new file
        echo $pkg > $path
        echo "SUCCESS: created $name and add $pkg to it's installed list"
        exit 0
    fi
# UNINSTALL
elif [[ $type == uninstall ]]; then
    # Path exists, check further
    if [[ -f $path ]]; then
        # Check if package exists
        index=$($PODDY/cmd/line/exists $path $pkg)
        # Delete line
        if [[ $index != false ]]; then
            command="'${index}d'"
            sed -i $command $path
            echo "STATUS: unregistered $pkg from install list"
        fi
        # number of lines in the document
        lines=$($PODDY/cmd/line/numbers $path)
        # lines are greater than 0, doesn't need uninstalled
        if [[ $lines == 0 ]]; then
            echo "STATUS: $name has no registered packages, deleting from system"
            # apt
            if [[ $location == apt ]]; then
                apt-get purge -y -qq $cmd
                apt-get autoremove -y -qq
            # py
            elif [[ $location == py ]]; then
                pip uninstall -y $cmd
            # node
            elif [[ $location == node ]]; then
                if [ ! -d $COMFY/custom_nodes/$name ]; then
                    rm -r $COMFY/custom_nodes/$name
                fi
            # model
            elif [[ $location == model ]]; then
                file=$COMFY/models/$model_location/$name
                if [[ -f $file ]]; then
                    rm $file
                    echo $name " deleted."
                fi
            fi
            rm -f $path
            echo "SUCCESS: $name removed"
        fi
        exit 0
    # Already deactive
    else
        echo "WARNING: $pkg already uninstalled"
        exit 1
    fi
fi