#!/bin/bash

#############################################
# FINDS THE DIFF BETWEEN TWO CATEGORIES AND
# CREATES INSTALL AND UNINSTALL FILES FOR 
# THOSE DIFFERENCES
#############################################

# the category to process: model | node | py | workflow | apt
category=${1}

# the path of the current installer
current_cat=$PODDY/active/tmp/current_${category}
new_cat=$PODDY/active/tmp/new_${category}
install_cat=$PODDY/active/tmp/install_${category}
uninstall_cat=$PODDY/active/tmp/uninstall_${category}

# Make found variable
found=false

# MAKE UNINSTALL LIST
# Loop lines of CURRENT category
while IFS= read -r current_line; do
    # Turn found variable off
    $found=false
    # Loop NEW category
    while IFS= read -r new_line; do
        # Line is found in both categories set found to true
        if [[ $new_line == $current_line ]]; then
            $found=true
        fi
    done < "$new_cat" # File to read from
    # If not found add to uninstall category
    if [[ $found == false ]]; then
        command='$a\'${current_line}
        sed -i $command $uninstall_cat
    fi
done < "$current_cat" # File to read from

# MAKE INSTALL LIST
# Loop lines of NEW category
while IFS= read -r new_line; do
    # Turn found variable off
    $found=false
    # Loop CURRENT category
    while IFS= read -r current_line; do
        # Line is found in both categories set found to true
        if [[ $new_line == $current_line ]]; then
            $found=true
        fi
    done < "$current_cat" # File to read from
    # If not found add to uninstall category
    if [[ $found == false ]]; then
        command='$a\'${new_line}
        sed -i $command $install_cat
    fi
done < "$new_cat" # File to read from