#!/bin/bash

#############################################
# EXTRACTS INSTALLER INTO CATEGORIES
#############################################

# the path of the installer
installer_path=${1}
# location: current | new | install | uninstall
type=${2:-current}

# Parse file
$PODDY/cmd/installer/parse_category $installer_path $PODDY/active/tmp/${type}_apt apt
$PODDY/cmd/installer/parse_category $installer_path $PODDY/active/tmp/${type}_py py
$PODDY/cmd/installer/parse_category $installer_path $PODDY/active/tmp/${type}_workflow workflow
$PODDY/cmd/installer/parse_category $installer_path $PODDY/active/tmp/${type}_node node
$PODDY/cmd/installer/parse_category $installer_path $PODDY/active/tmp/${type}_model model