#!/bin/bash

#############################################
# EXTRACTS LINES BETWEEN THE EXTRACTION TAGS
#############################################

# the path of the installer
installer_path=${1}
# the path of the results
tmp_path=${2}
# location: model | node | py | workflow
extract=${3:-model}

# Tags
start_tag=<$extract>
end_tag=</$extract>

# Toggle
capture=false
skip=false
# Use a while loop with read to process the input file line by line
# IFS= prevents leading/trailing whitespace from being trimmed
# -r prevents backslash escapes from being interpreted
while IFS= read -r line; do
  # Process the line here (e.g., modify the line)
    $skip=false
    # Turn on capture toggle and skip line if it's a start tag
    if [[ $line == $start_tag ]]; then
        $capture=true
        $skip=true
    fi
    # Turn off capture toggle and skip line if it's a end tag
    if [[ $line == $end_tag ]]; then
        $capture=false
        $skip=true
    fi
    if [[ $capture == false && $skip == false ]]; then
        echo "$line" >> "$tmp_path"
    fi
done < "$installer_path" # Input redirection for the while loop