#!/bin/bash

#############################################
# RUNS THE INSTALL OPTIONS STORED IN
# TMP FOLDER
#############################################

pkg=${1}
# mode = uninstall | install | update
mode=${2:-update}

if [[ $mode == update || $mode == uninstall ]]; then
    # apt
    while IFS= read -r line; do
        $PODDY/cmd/installer/activate uninstall apt $pkg $line
    done < "$PODDY/active/tmp/uninstall_apt" # File to read from

    # py
    while IFS= read -r line; do
        $PODDY/cmd/installer/activate uninstall py $pkg $line
    done < "$PODDY/active/tmp/uninstall_py" # File to read from

    # node
    while IFS= read -r line; do
        name=$(basename "$line")
        $PODDY/cmd/installer/activate uninstall node $pkg $line
    done < "$PODDY/active/tmp/uninstall_node" # File to read from

    # model
    while IFS= read -r line; do
        $PODDY/cmd/installer/activate uninstall model $pkg $line
    done < "$PODDY/active/tmp/uninstall_model" # File to read from

    # workflow
    while IFS= read -r line; do
        if [[ -f $PODDY/workflows/$line ]]; then
            if [[ -f $COMFY_WORKFLOW/$line ]]; then
                rm $COMFY_WORKFLOW/$line
            fi
            mv $PODDY/workflows/$line $COMFY_WORKFLOW/$line
        fi
    done < "$PODDY/active/tmp/uninstall_workflow" # File to read from
fi

if [[ $mode == update || $mode == install ]]; then
    # apt
    while IFS= read -r line; do
        $PODDY/cmd/installer/activate install apt $pkg $line
    done < "$PODDY/active/tmp/install_apt" # File to read from

    # py
    while IFS= read -r line; do
        $PODDY/cmd/installer/activate install py $pkg $line
    done < "$PODDY/active/tmp/install_py" # File to read from

    # node
    while IFS= read -r line; do
        name=$(basename "$line")
        $PODDY/cmd/installer/activate install node $pkg $line
    done < "$PODDY/active/tmp/install_node" # File to read from

    # model
    while IFS= read -r line; do
        $PODDY/cmd/installer/activate install model $pkg $line
    done < "$PODDY/active/tmp/install_model" # File to read from

    # workflow
    while IFS= read -r line; do
        if [[ -f $PODDY/workflows/$line ]]; then
            if [[ -f $COMFY_WORKFLOW/$line ]]; then
                rm $COMFY_WORKFLOW/$line
            fi
            mv $PODDY/workflows/$line $COMFY_WORKFLOW/$line
        fi
    done < "$PODDY/active/tmp/uninstall_workflow" # File to read from
fi
