#!/bin/bash
shift
# command = uninstall | install
command=${0:-uninstall}
shift

for pkg in "$@"; do
    # File exists, process
    if [[ -f $PODDY/installers/$pkg ]]; then
        # Prep tmp files
        $PODDY/cmd/installer/clean $pkg

        # Create tmp installer packages
        $PODDY/cmd/installer/parse_installer $PODDY/installers/$pkg $command current
        $PODDY/active/process $ITEM $command
    else
        exit 1
    fi
done
exit 0