#!/bin/bash
shift
err=0
for repository in "$@"; do
    name=$(basename $repository)
    echo "STATUS: Fetching $name"
    # Delete porta poddy directory if it exists
    if [[ -d $PORTA_PODDY ]]; then
        rm -R $PORTA_PODDY
    fi
    # Create porta poddy directory
    mkdir -p $PORTA_PODDY
    # Clone Github repo to porta poddy
    git clone $repository $PORTA_PODDY
    # Check if repository is correctly formatted
    if [[ -d $PORTA_PODDY/installer && -d $PORTA_PODDY/workflows ]]; then
        # Process Installers
        # Copy workflows
        for wf in $PORTA_PODDY/workflows; do
            cp $PORTA_PODDY/workflows/$wf $PODDY/workflows/$wf
        done
        for ITEM in $PORTA_PODDY/installer; do
            #Upgrade active package
            if [[ -f $PODDY/active/package/$ITEM ]]; then
                
                # Prep tmp files
                echo "STATUS: Upgrading active install"
                $PODDY/cmd/installer/clean $ITEM
                
                # extract installers to categories
                $PODDY/cmd/installer/parse_installer $PODDY/installer/$ITEM current
                $PODDY/cmd/installer/parse_installer $PORTA_PODDY/installer/$ITEM new
               
                # compare categories
                $PODDY/cmd/installer/compare_categories py
                $PODDY/cmd/installer/compare_categories workflow
                $PODDY/cmd/installer/compare_categories node
                $PODDY/cmd/installer/compare_categories model
                $PODDY/cmd/installer/compare_categories apt

                # remove old workflows
                while IFS= read -r wf; do
                    if [[ -f $PORTA_PODDY/workflows/$wf ]]; then
                        rm $PODDY/workflows/$wf
                    fi
                    if [[ -f $PODDY/workflows/$wf ]]; then
                        rm $COMFY_WORKFLOW/$wf
                    fi
                done < "$PODDY/active/tmp/uninstall_workflow" # File to read from
                # process install/uninstall
                $PODDY/cmd/installer/process $ITEM update
            fi
        done
        # Copy installers
        for inst in $PORTA_PODDY/installer; do
            cp $PORTA_PODDY/installer/$inst $PODDY/installer/$inst
        done
    else
        echo "ERROR: $name repository is not in the appropriate format"
        err=1
    fi
done
exit $err
