#!/bin/bash
echo "Custom Install Node"
name=$(basename $2)

if [[ -d $COMFY/custom_nodes/$name ]]; then
    echo "Uninstalling Custom Node: $name"
    rm -r $COMFY/custom_nodes/$name
else
    echo "NOT INSTALLED: $name"
fi