#!/bin/bash

echo "FLUSHING PODDY"
if [[ -d $PORTA_PODDY ]]; then
    rm -r $PORTA_PODDY
fi

mkdir -p $PORTA_PODDY

# DOWNLOAD
echo "Hydrating Poddy"
git clone https://github.com/ndrwmoss/going_poddy $PORTA_PODDY

echo "Copying Commands"
cp -r $PORTA_PODDY/cmd $PODDY/cmd
chmod -R +x $PODDY/cmd

echo "Copying Poddy"
cp -r $PORTA_PODDY/poddy /poddy
chmod +x /poddy

rm -r $PORTA_PODDY
/poddy update https://github.com/ndrwmoss/going_poddy
echo "Poddy Refreshed!"