#!/bin/bash

# Clear temp files
if [[ -f $PODDY/tmp/wiz_installed ]]; then
    rm $PODDY/tmp/wiz_installed
fi
touch $PODDY/tmp/wiz_installed
if [[ -f $PODDY/tmp/wiz_available ]]; then
    rm $PODDY/tmp/wiz_available
fi
touch $PODDY/tmp/wiz_available


# Iterate INSTALLERS DIRECTORY
for file in $PODDY/installers/*.installer; do
    if [[ -f $PODDY/active/$file.install ]]; then
        echo $file >> $PODDY/tmp/wiz_installed
    else
        echo $file >> $PODDY/tmp/wiz_available
    fi
done

exit 0
