#!/bin/bash
# Clear temp files
if [[ -f $PODDY/tmp/repo_input ]]; then
    rm $PODDY/tmp/repo_input
fi
touch $PODDY/tmp/repo_input

# Display the input box and redirect stderr to the temp file
dialog --title "External Repository" --inputbox "Type in the github address of the external repository you'd like to install:" 8 40 2> $PODDY/tmp/repo_input

# Get the exit code
exit_status=$?

# Get the input value from the temp file
user_input=$(cat $PODDY/tmp/repo_input)

if [ $exit_status -eq 0 ]; then
    $PODDY/cmd/upgrade $user_input
fi
exit 0