#!/bin/bash
# ${1}=directory
# ${2}=name
# ${3}=url

# Prep location for download
local dir=$COMFY_MODELS/${1}
local file=${dir}/${2}
mkdir -p $dir

# Extract domain name
local domain=$(echo "$3" | sed -E 's|(https://)?([^/]+).*|\2|')
local url=${3}
domain=$(basename -s ".com" $domain)
domain=$(basename -s ".co" $domain)


# Check if already installed


# Add to install list

# Update install list



# Download
if [[ $domain == "civitai" ]]; then
    local token=${CIVITAI:-"none"}
    # CIVITAI
    if [[ $token == "none" ]]; then
        echo "NO CIVIAI API FOUND!!! $2 requires the CIVITAI environmental variable set to your civitai api"
    else
        url="${3}&token=${CIVITAI}"
        echo "downloading ${3} to ${file}"
        wget -O ${file} ${url}
    fi
else
    # HUGGINGFACE
    echo "downloading ${3} to ${file}"
    wget -O ${file} ${url}
fi


