#!/bin/bash
# ${1}=name
# ${2}=directory
# ${3}=url

# Prep location for download
name=${1}
sub_directory=${2}
full_url=${3}
directory=$COMFY_MODELS/${sub_directory}
file=${sub_directory}/${1}
mkdir -p $directory

# Bail if already exists
if [[ -f $file ]]; then
    echo $name " already exists, no need to double flush."
    exit 0
fi

# Extract domain name
domain=$(echo "$full_url" | sed -E 's|(https://)?([^/]+).*|\2|')
url=$full_url
domain=$(basename -s ".com" $domain)
domain=$(basename -s ".co" $domain)

# Download
if [[ $domain == "civitai" ]]; then
    token=${CIVITAI:-"none"}
    # CIVITAI
    if [[ $token == "none" ]]; then
        echo "NO FLUSHIN' CIVITAI API FOUND!!! $name requires the CIVITAI environmental variable set"
        exit 1
    else
        url="$full_url&token=$CIVITAI"
        echo "downloading $full_url to $file"
        wget -O $file $url
        exit 0
    fi
else
    # HUGGINGFACE
    echo "downloading $full_url to $file"
    wget -O $file $full_url
    exit 0
fi