#!/bin/bash
url=${1:-none}
if [[ $url != none ]]; then
    name=$(basename "$url")
    if [ ! -d $COMFY/custom_nodes/$name ]; then
        echo "CUSTOM NODES: ${name}"
        git clone $url $COMFY/custom_nodes/$name
    fi
fi
exit 0