#!/bin/bash
name=$(basename $1)
if [ ! -d $COMFY/custom_nodes/$name ]; then
    echo "INSTALLING CUSTOM NODE: $name"
    git clone $1 $COMFY/custom_nodes/$name
else
    echo "ALREADY INSTALLED: $name"
fi
exit 0