#!/bin/bash
echo "Custom Install Node"
name=$(basename ${1})
if [ ! -d $COMFY/custom_nodes/$name ]; then
    echo "Installing Custom Node: $name"
    git clone ${1} $COMFY/custom_nodes/$name
else
    echo "$name already exists"
fi