#!/bin/bash

function old {
    # --- Update Comfy ---
    if [[ -f ${COMFY}/requirements.txt ]]; then
        echo "Updating ComfyUI"
        pip install -r ${COMFY}/requirements.txt
    fi
    # --- Install Manager ---
    if [[ ! -d ${COMFY_NODES}/ComfyUI-Manager ]]; then
        echo "Installing ComfyUI-Manager"
        git clone https://github.com/Comfy-Org/ComfyUI-Manager
    else
        echo "ComfyUI already present in /workspace; skipping copy."
    fi
    # --- Update Manager ---
    if [[ -f ${COMFY_NODES}/ComfyUI-Manager/requirements.txt ]]; then
        echo "Updating ComfyUI"
        pip install -r ${COMFY_NODES}/ComfyUI-Manager/requirements.txt
    fi
}
cd $COMFY
git clone https://github.com/comfyanonymous/ComfyUI.git .
pip install -r requirements.txt
cd $COMFY/custom_nodes
mkdir -p $COMFY/custom_nodes/ComfyUI-Manager
cd $COMFY/custom_nodes/ComfyUI-Manager
git clone https://github.com/Comfy-Org/ComfyUI-Manager .
pip install -r requirements.txt
mkdir -p $COMFY_WORKFLOW
cd /