#!/bin/bash

echo "INIT: CUDA"
$PODDY/boot/cuda

rep=${REPO:-"none"}
$PODDY/boot/system

echo "INIT: COMFY"
$PODDY/boot/comfy

# Runs update.
if [[ $rep == "none" ]]; then
    $PODDY/boot/update
elif [[ $rep == test ]]; then
    $PODDY/boot/update
    $PODDY/boot/update test
else
    $PODDY/boot/update
    $PODDY/boot/update $rep
fi

# Runs installers if PREINSTALL is set to a non-empty string.
pre=${PREINSTALL:-"none"}
if [[ $pre != "none" ]]; then
    echo "INIT: installing selected Going Poddy packages"
    /poddy i $pre
else
    echo "INIT: Going Poddy packages selected. To install packages open a terminal and type /poddy to open the Going Poddy wizard where you can select packages to install."
fi

echo "INIT: POPULATING YOUR PODDY"
pip install --upgrade pip
pip install onnxruntime-gpu

echo "INIT: SAGE"
$PODDY/boot/sage

echo "INIT: SSH"
$PODDY/boot/ssh

echo "INIT: NGINX"
$PODDY/boot/nginx

echo "INIT: JUPYTER"
$PODDY/boot/jupyter

echo "INIT COMPLETE: STARTING YOUR COMFY ON PORT 8188"
python $COMFY/main.py --use-sage-attention --listen --port=8188