#!/bin/bash
boot=$PODDY/boot

/poddy update

echo "INIT: POPULATING YOUR PODDY"
python -m pip install --upgrade pip
python -m pip install triton
python -c "import triton; print(triton.__version__)"

echo "INIT: CUDA"
$boot/cuda

echo "INIT: SAGE"
$boot/sage

echo "INIT: COMFY"
$boot/comfy

echo "INIT: SSH"
$boot/ssh

echo "INIT: NGINX"
$boot/nginx

echo "INIT: JUPYTER"
$boot/jupyter

# Runs installers if INSTALL_PODDY is set to a non-empty string.
pre=${PREINSTALL:-"none"}
if [[ $pre != "none" ]]; then
    echo "INIT: Pre-Installing packages"
    /poddy add $pre
else
    echo "INIT: No pre installation packages selected."
fi
echo "INIT COMPLETE: STARTING YOUR COMFY"
python /workspace/ComfyUI/main.py --port=8188