#!/bin/bash
boot=$PODDY/boot

echo "INIT STAGE 1: POPULATING YOUR PODDY"
#python -m pip install --upgrade pip

echo "INIT STAGE 2: CHECKING YOUR CUDA"
#$boot/cuda

echo "INIT STAGE 3: INSTALLING YOUR SAGE"
#$boot/sage

echo "INIT STAGE 4: INSTALLING YOUR COMFY"
#$boot/comfy

echo "INIT STAGE 5: STARTING YOUR SSH"
#$boot/ssh

echo "INIT STAGE 6: STARTING YOUR NGINX"
#$boot/nginx

echo "INIT STAGE 7: STARTING YOUR JUPYTER"
#$boot/jupyter

mkdir -p $COMFY_WORKFLOW

/poddy update

# Runs installers if INSTALL_PODDY is set to a non-empty string.
pre=${PREINSTALL:-"none"}
if [[ $pre != "none" ]]; then
    echo "Pre-Installing packages"
    /poddy add $pre
else
    echo "No pre installation packages selected."
fi
echo "INIT COMPLETE: STARTING YOUR COMFY"
#python /workspace/ComfyUI/main.py --port=8188