#!/bin/bash

echo "UPDATE: GETTING A FRESH PODDY"
if [[ -d $PORTA_PODDY ]]; then
    rm -r $PORTA_PODDY
fi
mkdir -p $PORTA_PODDY
git clone https://github.com/ndrwmoss/going_poddy $PORTA_PODDY
\cp -r $PORTA_PODDY/cmd $PODDY
\cp $PORTA_PODDY/poddy /poddy

chmod -R +x $PODDY/cmd
chmod -R +x /poddy

rm -r $PORTA_PODDY
echo "UPDATE: CLEANED PODDY"