#!/bin/bash
location=${1:-https://github.com/ndrwmoss/going_poddy}
if [[ $1 == test ]]; then
    location=https://github.com/ndrwmoss/testing_poddy
fi
echo "UPDATING $location"
if [[ -d $PORTA_PODDY ]]; then
    rm -r $PORTA_PODDY
fi
mkdir -p $PORTA_PODDY
git clone $location $PORTA_PODDY

if [[ -d $PORTA_PODDY/installers && -d $PORTA_PODDY/workflows]]; then
    \cp -r $PORTA_PODDY/installers $PODDY
    \cp -r $PORTA_PODDY/workflows $PODDY
    rm -r $PORTA_PODDY
    echo "UPDATE COMPLETE"
else
    echo "INVALID REPOSITORY"
fi