#!/bin/bash
echo "FLUSHING PODDY"
if [[ -d $PORTA_PODDY ]]; then
    rm -r $PORTA_PODDY
fi
cd $PODDY

# DOWNLOAD

echo "Hydrating Poddy"
git clone https://github.com/ndrwmoss/going_poddy

if [[ -d ${PODDY}/cmd ]]; then
    rm -R ${PODDY}/cmd
fi
cp -r $PORTA_PODDY/cmd $PODDY/cmd

if [[ -d ${PODDY}/installers ]]; then
    rm -R ${PODDY}/installers
fi
cp -r $PORTA_PODDY/installers $PODDY/installers

if [[ -d ${PODDY}/workflows ]]; then
    rm -R ${PODDY}/workflows
fi
cp -r $PORTA_PODDY/workflows $PODDY/workflows

if [[ -f /poddy ]]; then
    rm /poddy
fi
cp -r $PORTA_PODDY/poddy /poddy

chmod +x $PODDY/poddy
chmod -R +x $PODDY/cmd
chmod -R +x $PODDY/installers

echo "Poddy Refreshed!"