#!/bin/bash

# INSTALL PYTHON SCRIPTS
echo "SCRIPT: python packages"
$1/py pyloudnorm

# INSTALL CUSTOM NODES
echo "SCRIPT: custom nodes"
# $1/node url
$1/node https://github.com/Kosinkadink/ComfyUI-VideoHelperSuite
$1/node https://github.com/kijai/ComfyUI-KJNodes
$1/node https://github.com/kijai/ComfyUI-WanVideoWrapper
$1/node https://github.com/kijai/ComfyUI-MelBandRoFormer


# COPY MODELS
echo "SCRIPT: models"
# $1/model name folder url
$1/model MelBandRoformer_fp16.safetensors diffusion_models https://huggingface.co/Kijai/MelBandRoFormer_comfy/resolve/main/MelBandRoformer_fp16.safetensors
$1/model umt5-xxl-enc-bf16.safetensors text_encoders https://huggingface.co/Kijai/WanVideo_comfy/resolve/main/umt5-xxl-enc-bf16.safetensors
$1/model Wan2_1-InfiniTetalk-Single_fp16.safetensors diffusion_models https://huggingface.co/Kijai/WanVideo_comfy/resolve/main/InfiniteTalk/Wan2_1-InfiniTetalk-Single_fp16.safetensors
$1/model wav2vec2-chinese-base_fp16.safetensors wav2vec2 https://huggingface.co/Kijai/wav2vec2_safetensors/resolve/main/wav2vec2-chinese-base_fp16.safetensors
$1/model lightx2v_I2V_14B_480p_cfg_step_distill_rank64_bf16.safetensors loras https://huggingface.co/Kijai/WanVideo_comfy/resolve/main/Lightx2v/lightx2v_I2V_14B_480p_cfg_step_distill_rank64_bf16.safetensors
$1/model Wan14Bi2vFusioniX.safetensors diffusion_models https://huggingface.co/vrgamedevgirl84/Wan14BT2VFusioniX/resolve/main/Wan14Bi2vFusioniX.safetensors
$1/model wan_2.1_vae.safetensors vae https://huggingface.co/Comfy-Org/Wan_2.1_ComfyUI_repackaged/resolve/main/split_files/vae/wan_2.1_vae.safetensors
$1/model clip_vision_h.safetensors clip_vision https://huggingface.co/Comfy-Org/Wan_2.1_ComfyUI_repackaged/resolve/main/split_files/clip_vision/clip_vision_h.safetensors

# COPY WORKFLOW
echo "SCRIPT: workflows"
$1/workflow vid_lipsync