#!/bin/bash
# type=${1} models | workflows | custom_nodes
# filename=${2} variable
# model_location=${3} clips | text_encoders | diffusion_models ...
if [[ ${1} == "models" && -f ${PODDY_INSTALLED}/${1}/${3}/${2} ]]; then
    return 1
else if [[ -f ${PODDY_INSTALLED}/${1}/${2} ]]; then
    return 1
fi
return 0