#!/bin/bash
# type=${1}
# filename=${2}
# model_location=${3}
if [[ ${1} == "models" ]]; then
    return 1
else if [[ ${1} == "custom_nodes" ]]; then
    return 1
fi
return 0


if [[ ${1} == "models" && -f ${PODDY_INSTALLED}/${1}/${3}/${2} ]]; then
    return 1
else if [[ -f ${PODDY_INSTALLED}/${1}/${2} ]]; then
    return 1
fi
return 0