#!/bin/bash
set -e # Exit the script if any statement returns a non-true return
local install="$PODDY/command/${1:-install}"

# INSTALL PYTHON SCRIPTS
echo "SCRIPT: ${1}ing python packages"

# COPY WORKFLOW
echo "SCRIPT: ${1}ing workflows"
"${install}"/workflow img_clothing_transfer.json

# INSTALL CUSTOM NODES
echo "SCRIPT: ${1}ing custom nodes"
# "${install}"/node url
"${install}"/node https://github.com/rgthree/rgthree-comfy
"${install}"/node https://github.com/yolain/ComfyUI-Easy-Use
"${install}"/node https://github.com/kijai/ComfyUI-KJNodes
"${install}"/node https://github.com/ssitu/ComfyUI_UltimateSDUpscale
"${install}"/node https://github.com/Smirnov75/ComfyUI-mxToolkit

# COPY MODELS
echo "SCRIPT: ${1}ing custom models"
# "${install}"/model folder name url
"${install}"/model diffusion_models qwen_image_edit_fp8_e4m3fn.safetensors https://huggingface.co/Comfy-Org/Qwen-Image-Edit_ComfyUI/resolve/main/split_files/diffusion_models/qwen_image_edit_fp8_e4m3fn.safetensors
"${install}"/model directory juggernautXL_juggXIByRundiffusion.safetensors https://huggingface.co/misri/juggernautXL_juggXIByRundiffusion/resolve/main/juggernautXL_juggXIByRundiffusion.safetensors 
"${install}"/model vae qwen_image_vae.safetensors https://huggingface.co/Comfy-Org/Qwen-Image_ComfyUI/resolve/main/split_files/vae/qwen_image_vae.safetensors
"${install}"/model text_encoders qwen_2.5_vl_7b_fp8_scaled.safetensors https://huggingface.co/Comfy-Org/Qwen-Image_ComfyUI/resolve/main/split_files/text_encoders/qwen_2.5_vl_7b_fp8_scaled.safetensors
"${install}"/model loras Qwen-Image-Lightning-4steps-V2.0.safetensors https://huggingface.co/lightx2v/Qwen-Image-Lightning/resolve/main/Qwen-Image-Lightning-4steps-V2.0.safetensors
"${install}"/model loras clothes_tryon_qwen-edit-lora.safetensors "https://civitai.com/api/download/models/2196278?type=Model&format=SafeTensor"
"${install}"/model loras extract-outfit_v3.safetensors https://huggingface.co/datasets/dubsta/xmas/resolve/main/extract-outfit_v3.safetensors
"${install}"/model upscale_models RealESRGAN_x2.pth https://huggingface.co/dtarnow/UPscaler/resolve/main/RealESRGAN_x2plus.pth