#!/bin/bash
set -e # Exit the script if any statement returns a non-true return
local install="/going_poddy/init"

# INSTALL PYTHON SCRIPTS
echo "SCRIPT: Setup"
pip install pyloudnorm

# COPY WORKFLOW
echo "SCRIPT: Fetching Workflow"
"${install}"/workflow vid_lipsync.json

# INSTALL CUSTOM NODES
echo "SCRIPT: Fetching Custom Nodes"
# "${install}"/node url
"${install}"/node https://github.com/Kosinkadink/ComfyUI-VideoHelperSuite
"${install}"/node https://github.com/kijai/ComfyUI-KJNodes
"${install}"/node https://github.com/kijai/ComfyUI-WanVideoWrapper
"${install}"/node https://github.com/kijai/ComfyUI-MelBandRoFormer

# Update custom nodes
"${install}"/update_nodes.sh

# COPY MODELS
echo "SCRIPT: Fetching Models"
# "${install}"/model folder name url civitai
"${install}"/model diffusion_models MelBandRoformer_fp16.safetensors https://huggingface.co/Kijai/MelBandRoFormer_comfy/resolve/main/MelBandRoformer_fp16.safetensors
"${install}"/model text_encoders umt5-xxl-enc-bf16.safetensors https://huggingface.co/Kijai/WanVideo_comfy/resolve/main/umt5-xxl-enc-bf16.safetensors
"${install}"/model diffusion_models Wan2_1-InfiniTetalk-Single_fp16.safetensors https://huggingface.co/Kijai/WanVideo_comfy/resolve/main/InfiniteTalk/Wan2_1-InfiniTetalk-Single_fp16.safetensors
"${install}"/model wav2vec2 wav2vec2-chinese-base_fp16.safetensors https://huggingface.co/Kijai/wav2vec2_safetensors/resolve/main/wav2vec2-chinese-base_fp16.safetensors
"${install}"/model loras lightx2v_I2V_14B_480p_cfg_step_distill_rank64_bf16.safetensors https://huggingface.co/Kijai/WanVideo_comfy/resolve/main/Lightx2v/lightx2v_I2V_14B_480p_cfg_step_distill_rank64_bf16.safetensors
"${install}"/model diffusion_models Wan14Bi2vFusioniX.safetensors https://huggingface.co/vrgamedevgirl84/Wan14BT2VFusioniX/resolve/main/Wan14Bi2vFusioniX.safetensors
"${install}"/model vae wan_2.1_vae.safetensors https://huggingface.co/Comfy-Org/Wan_2.1_ComfyUI_repackaged/resolve/main/split_files/vae/wan_2.1_vae.safetensors
"${install}"/model clip_vision clip_vision_h.safetensors https://huggingface.co/Comfy-Org/Wan_2.1_ComfyUI_repackaged/resolve/main/split_files/clip_vision/clip_vision_h.safetensors

echo "DONE: RESTART COMFYUI FOR CHANGES TO TAKE EFFECT"