#!/bin/bash
set -e # Exit the script if any statement returns a non-true return
local dir="/going_poddy/command/${1:-install}"

# INSTALL PYTHON SCRIPTS
echo "SCRIPT: Setup"

# COPY WORKFLOW
echo "SCRIPT: Fetching Workflow"
"${dir}"/workflow img_clothing_transfer.json

# INSTALL CUSTOM NODES
echo "SCRIPT: Fetching Custom Nodes"
# "${dir}"/node url
"${dir}"/node https://github.com/rgthree/rgthree-comfy
"${dir}"/node https://github.com/yolain/ComfyUI-Easy-Use
"${dir}"/node https://github.com/kijai/ComfyUI-KJNodes
"${dir}"/node https://github.com/ssitu/ComfyUI_UltimateSDUpscale
"${dir}"/node https://github.com/Kosinkadink/ComfyUI-VideoHelperSuite
"${dir}"/node https://github.com/cubiq/ComfyUI_essentials
"${dir}"/node https://github.com/cubiq/ComfyUI-Florence2

# COPY MODELS
echo "SCRIPT: Fetching Models"
# "${dir}"/model folder name url civitai
"${dir}"/model diffusion_models wan2.2_t2v_low_noise_14B_fp8_scaled.safetensors https://huggingface.co/Comfy-Org/Wan_2.2_ComfyUI_Repackaged/resolve/main/split_files/diffusion_models/wan2.2_t2v_low_noise_14B_fp8_scaled.safetensors
"${dir}"/model loras low_noise_model.safetensors https://huggingface.co/lightx2v/Wan2.2-Lightning/resolve/main/Wan2.2-T2V-A14B-4steps-lora-rank64-Seko-V2.0/low_noise_model.safetensors
"${dir}"/model clip low_noise_model.safetensors https://huggingface.co/Comfy-Org/Wan_2.1_ComfyUI_repackaged/resolve/main/split_files/text_encoders/umt5_xxl_fp8_e4m3fn_scaled.safetensors
"${dir}"/model vae wan_2.1_vae.safetensors https://huggingface.co/Comfy-Org/Wan_2.1_ComfyUI_repackaged/resolve/main/split_files/vae/wan_2.1_vae.safetensors
"${dir}"/model upscale_models RealESRGAN_x2.pth https://huggingface.co/ai-forever/Real-ESRGAN/resolve/main/RealESRGAN_x2.pth
"${dir}"/model upscale_models stock_photography_wan22_LOW_v1.safetensors "https://civitai.com/api/download/models/2179627?type=Model&format=SafeTensor" 1

# Update custom nodes
/going_poddy/command/init/update_nodes.sh

echo "DONE: RESTART COMFYUI FOR CHANGES TO TAKE EFFECT"