#!/bin/bash
# parameter 1 = install | uninstall
process=$PODDY/${1:-install}
echo $process

# INSTALL APT
echo "SCRIPT: apt packages"
# $process/apt apt

# INSTALL PYTHON SCRIPTS
echo "SCRIPT: python packages"
# $process/py pyt

# COPY WORKFLOW
echo "SCRIPT: workflows"
# $process/workflow workflow
$process/workflow img_clothing_transfer

# INSTALL CUSTOM NODES
echo "SCRIPT: custom nodes"
# $process1/node url
$process/node https://github.com/rgthree/rgthree-comfy
$process/node https://github.com/yolain/ComfyUI-Easy-Use
$process/node https://github.com/kijai/ComfyUI-KJNodes
$process/node https://github.com/ssitu/ComfyUI_UltimateSDUpscale
$process/node https://github.com/Smirnov75/ComfyUI-mxToolkit

# COPY MODELS
echo "SCRIPT: models"
# $process/model name folder url
$process/model qwen_image_edit_fp8_e4m3fn.safetensors diffusion_models https://huggingface.co/Comfy-Org/Qwen-Image-Edit_ComfyUI/resolve/main/split_files/diffusion_models/qwen_image_edit_fp8_e4m3fn.safetensors
$process/model juggernautXL_juggXIByRundiffusion.safetensors diffusion_models https://huggingface.co/misri/juggernautXL_juggXIByRundiffusion/resolve/main/juggernautXL_juggXIByRundiffusion.safetensors
$process/model qwen_image_vae.safetensors vae https://huggingface.co/Comfy-Org/Qwen-Image_ComfyUI/resolve/main/split_files/vae/qwen_image_vae.safetensors
$process/model qwen_2.5_vl_7b_fp8_scaled.safetensors text_encoders https://huggingface.co/Comfy-Org/Qwen-Image_ComfyUI/resolve/main/split_files/text_encoders/qwen_2.5_vl_7b_fp8_scaled.safetensors
$process/model Qwen-Image-Lightning-4steps-V2.0.safetensors loras https://huggingface.co/lightx2v/Qwen-Image-Lightning/resolve/main/Qwen-Image-Lightning-4steps-V2.0.safetensors
$process/model clothes_tryon_qwen-edit-lora.safetensors loras https://civitai.com/api/download/models/2196278?type=Model&format=SafeTensor&token=${CIVITAI}
$process/model extract-outfit_v3.safetensors loras https://huggingface.co/datasets/dubsta/xmas/resolve/main/extract-outfit_v3.safetensors
$process/model RealESRGAN_x2.pth upscale_models https://huggingface.co/dtarnow/UPscaler/resolve/main/RealESRGAN_x2plus.pth

echo "COMPLETE"