#!/bin/bash

# SETUP
c=$PODDY/cmd/${1:-install}

# WORKFLOWS
$c/workflow vid_character_and_bg_replace
$c/workflow vid_character_replace

# NODES
$c/node https://github.com/Kosinkadink/ComfyUI-VideoHelperSuite
$c/node https://github.com/kijai/ComfyUI-KJNodes
$c/node https://github.com/kijai/ComfyUI-WanVideoWrappers
$c/node https://github.com/kijai/ComfyUI-WanAnimatePreprocess
$c/node https://github.com/un-seen/comfyui-tensorops
$c/node https://github.com/kijai/ComfyUI-segment-anything-2

# MODELS
$c/model Wan2_2-Animate-14B_fp8_e4m3fn_scaled_KJ.safetensors diffusion_models https://huggingface.co/Kijai/WanVideo_comfy_fp8_scaled/resolve/main/Wan22Animate/Wan2_2-Animate-14B_fp8_e4m3fn_scaled_KJ.safetensors
$c/model umt5-xxl-enc-bf16.safetensors text_encoders https://huggingface.co/Kijai/WanVideo_comfy/resolve/main/umt5-xxl-enc-bf16.safetensors
$c/model Wan2_1_VAE_bf16.safetensors vae https://huggingface.co/Kijai/WanVideo_comfy/resolve/main/Wan2_1_VAE_bf16.safetensors
$c/model clip_vision_h.safetensors clip_vision https://huggingface.co/Comfy-Org/Wan_2.1_ComfyUI_repackaged/resolve/main/split_files/clip_vision/clip_vision_h.safetensors
$c/model sam2.1_hiera_base_plus.safetensors sam2 https://huggingface.co/Kijai/sam2-safetensors/resolve/main/sam2.1_hiera_base_plus.safetensors
$c/model WanAnimate_relight_lora_fp16.safetensors loras https://huggingface.co/Kijai/WanVideo_comfy/resolve/main/LoRAs/Wan22_relight/WanAnimate_relight_lora_fp16.safetensors
$c/model lightx2v_I2V_14B_480p_cfg_step_distill_rank64_bf16.safetensors loras https://huggingface.co/Kijai/WanVideo_comfy/resolve/main/Lightx2v/lightx2v_I2V_14B_480p_cfg_step_distill_rank64_bf16.safetensors
$c/model vitpose-l-wholebody.onnx detection https://huggingface.co/JunkyByte/easy_ViTPose/resolve/main/onnx/wholebody/vitpose-l-wholebody.onnx
$c/model yolov10m.onnx detection https://huggingface.co/Wan-AI/Wan2.2-Animate-14B/resolve/main/process_checkpoint/det/yolov10m.onnx
