#!/bin/bash

#################################################################################
#   Extracts a category's (apt, py, workflow, node, model) item list            
#   into a single file to easily iterate through all items currently installed  
#   by category. The file is stored as the category's name and                  
#   is stored in the tmp folder. Example: $PODDY/tmp/installed/apt              
#################################################################################

# Clear temp files
if [[ -f $PODDY/tmp/installed ]]; then
    rm $PODDY/tmp/installed
fi
touch $PODDY/tmp/installed

# Iterate ACTIVE DIRECTORY
for file in $PODDY/active/*; do
    if [ -f "$file" ]; then
        echo "Checking: $file"
        # Iterate CURRENT FILE
        while IFS= read -r line; do
            words=($line)
            command=${words[0]}
            # Check CURRENT LINE
            if [[ $command == apt || $command == py || $command == model || $command == node || $command == workflow ]]; then
                # Check if line already exists
                exists=$($PODDY/cmd/line_exists $line $PODDY/tmp/installed)
                if [[ $exists == false ]]; then
                    # Write to output file if line doesn't exist
                    echo $line >> $PODDY/tmp/installed
                fi
            fi
        done < $file
    fi
done