#!/bin/bash

if [[ -d $PODDY/active ]]; then
    for file in $PODDY/active/*; do
        while IFS= read -r line; do
            if [[ $line == $1 ]]; then
                echo "true"
                exit 0
            fi
        done < $file
    done
else
    echo "active doesn't exist"
    mkdir -p $PODDY/active
fi
echo "false"
exit 0