#!/bin/bash

#################################################################################
#   Compares the pkg item list to a list of all the items currently installed   
#   and makes a file called 'uninstall.tmp' in the tmp directory. This file has 
#   a list of all the items that need uninstalled without uninstalling items    
#   needed by other packages                                                    
#################################################################################

pkg=${1:-none}

if [[ ! -f $PODDY/active/$pkg && -f $PODDY/installers/$pkg ]]; then
    # Clear temp files
    if [[ -f $PODDY/tmp/install ]]; then
        rm $PODDY/tmp/install
    fi
    if [[ -f $PODDY/tmp/uninstall ]]; then
        rm $PODDY/tmp/uninstall
    fi
    touch $PODDY/tmp/install
    touch $PODDY/tmp/uninstall

    # Make already installed list
    echo "INSTALL: Making Installed List"
    $PODDY/cmd/get_currently_installed

    # Compare $pkg against installed list, collecting any lines that are not already installed
    echo "INSTALL: Checking installed packages for identical items"
    # Iterate lines in install pkg
    while IFS= read -r line; do
        add_to_file=true
        # Iterate installed file
        echo "INSTALL: checking $active_file"
        # Iterate CURRENT FILE
        while IFS= read -r other_pkg_line; do
            if [[ $other_pkg_line == $line ]]; then
                add_to_file=false
            fi
        done < $PODDY/tmp/installed
        if [[ $add_to_file == true ]]; then
            echo $line >> $PODDY/tmp/install
        fi
    done < $PODDY/installers/$pkg
    
    # Run installers
    $PODDY/cmd/process

    # Copy pkg to $PODDY/active
    cp $PODDY/installers/$pkg $PODDY/active/$pkg

    echo "SUCCESSFULLY INSTALLED: $pkg"
fi
