#!/bin/bash
location=${1}
filename=${2}
pkg=${3:-"fecal_transplant"}
path=$location/$filename
if [[ -f $path ]]; then
    exit 1
else
    mkdir -p $location
    if [[ $pkg != "fecal_transplant" ]]; then
        echo $pkg > $path
    else
        touch $path
    fi
    exit 0
fi