#!/bin/bash
name=${1:-none}
folder=${2:-vae}
url=${3}
if [[ $cmd != none ]]; then
    echo "MODEL: $name"
    directory=$COMFY/models/$folder
    file=$directory/$name
    mkdir -p $directory
    # Bail if already exists
    if [[ -f $file ]]; then
        echo  "WARNING: $name already exists."
        exit 0
    fi
    # Extract domain name
    domain=$(echo "$url" | sed -E 's|(https://)?([^/]+).*|\2|')
    domain=$(basename -s ".com" $domain)
    domain=$(basename -s ".co" $domain)
    # Download
    if [[ $domain == "civitai" ]]; then
        # CIVITAI
        token=${CIVITAI:-"none"}
        civitai_url="$url&token=$CIVITAI"
        if [[ $token == "none" ]]; then
            echo "$name requires the CIVITAI environmental variable set"
            exit 1
        else
            echo "downloading $url to $file"
            wget -O $file $civitai_url
        fi
    else
        # HUGGINGFACE
        echo "downloading $url to $file"
        wget -O $file $url
    fi
fi
exit 0