#!/bin/bash
set -e # Exit the script if any statement returns a non-true return
local install="/going_poddy/init"

# INSTALL PYTHON SCRIPTS
echo "SCRIPT: Setup"

# COPY WORKFLOW
echo "SCRIPT: Fetching Workflow"
"${install}"/workflow img_clothing_transfer.json

# INSTALL CUSTOM NODES
echo "SCRIPT: Fetching Custom Nodes"
# "${install}"/node url
"${install}"/node https://github.com/Comfy-Org/ComfyUI-Manager
"${install}"/node https://github.com/rgthree/rgthree-comfy
"${install}"/node https://github.com/yolain/ComfyUI-Easy-Use
"${install}"/node https://github.com/kijai/ComfyUI-KJNodes
"${install}"/node https://github.com/ssitu/ComfyUI_UltimateSDUpscale
"${install}"/node https://github.com/Kosinkadink/ComfyUI-VideoHelperSuite
"${install}"/node https://github.com/cubiq/ComfyUI_essentials
"${install}"/node https://github.com/cubiq/ComfyUI-Florence2

# Update custom nodes
"${install}"/update_nodes.sh

# COPY MODELS
echo "SCRIPT: Fetching Models"
# "${install}"/model folder name url civitai
"${install}"/model diffusion_models wan2.2_t2v_low_noise_14B_fp8_scaled.safetensors https://huggingface.co/Comfy-Org/Wan_2.2_ComfyUI_Repackaged/resolve/main/split_files/diffusion_models/wan2.2_t2v_low_noise_14B_fp8_scaled.safetensors
"${install}"/model loras low_noise_model.safetensors https://huggingface.co/lightx2v/Wan2.2-Lightning/resolve/main/Wan2.2-T2V-A14B-4steps-lora-rank64-Seko-V2.0/low_noise_model.safetensors
"${install}"/model clip low_noise_model.safetensors https://huggingface.co/Comfy-Org/Wan_2.1_ComfyUI_repackaged/resolve/main/split_files/text_encoders/umt5_xxl_fp8_e4m3fn_scaled.safetensors
"${install}"/model vae wan_2.1_vae.safetensors https://huggingface.co/Comfy-Org/Wan_2.1_ComfyUI_repackaged/resolve/main/split_files/vae/wan_2.1_vae.safetensors
"${install}"/model upscale_models RealESRGAN_x2.pth https://huggingface.co/ai-forever/Real-ESRGAN/resolve/main/RealESRGAN_x2.pth
"${install}"/model upscale_models stock_photography_wan22_LOW_v1.safetensors "https://civitai.com/api/download/models/2179627?type=Model&format=SafeTensor" 1

echo "DONE: RESTART COMFYUI FOR CHANGES TO TAKE EFFECT"