#!/bin/bash
url=${1:-none}
if [[ $url != none ]]; then
    name=$(basename "$url")
    echo "CUSTOM NODE: $cmd"
    if [ -d $COMFY/custom_nodes/$name ]; then
        rm -r $COMFY/custom_nodes/$name
    fi
fi
exit 0